name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Release Build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest commit
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: sdkmanager "ndk;23.2.8568313"

      - name: Export Android variables
        run: |
         echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
         echo "ANDROID_SDK=$ANDROID_HOME" >> $GITHUB_ENV
         echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
         echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/23.2.8568313" >> $GITHUB_ENV
         echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.2.8568313" >> $GITHUB_ENV
         echo "ANDROID_NDK=$ANDROID_HOME/ndk/23.2.8568313" >> $GITHUB_ENV
         echo "HXCPP_COMPILE_CACHE=$HOME/.hxcpp" >> $GITHUB_ENV
         
      - name: Setup project libraries (libs.xml)
        run: |
          haxe -cp commandline --run Main setup -s

      - name: Setup Lime for Android
        run: haxelib run lime setup android

      - name: Build Android (verbose)
        run: |
          mkdir -p build-logs
          haxelib run lime build android -release -Dandroid64 -v 2>&1 | tee build-logs/build.log

      - name: Show actual errors
        run: |
          echo "===== REAL ERRORS ====="
          grep -iE "error|exception|fail" build-logs/build.log | tail -n 50 || true

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: Android Build Logs
          path: build-logs/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android APK
          path: export/release/android/bin/*.apk
