name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Release Build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4

      # -------------------------
      # Java 17 (You require this)
      # -------------------------
      - name: Setting up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # -------------------------
      # Haxe
      # -------------------------
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      # -------------------------
      # Android SDK
      # -------------------------
      - name: Setting up Android SDK
        uses: android-actions/setup-android@v3

      # Install NDK (REQUIRED for hxcpp Android)
      - name: Installing Android NDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager "ndk;25.2.9519653"

      # -------------------------
      # Environment Variables
      # -------------------------
      - name: Setting Android environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      # -------------------------
      # Restore build cache (same style as Windows)
      # -------------------------
      - name: Restore existing build cache
        uses: actions/cache@v4.2.3
        with:
          key: cache-build-android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/
            ~/.hxcpp

      - run: |
          echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

      # -------------------------
      # Engine setup (same as Windows)
      # -------------------------
      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s

      - name: Lime Android Setup
        run: |
          haxelib run lime setup android

      - name: Building the game
        run: |
          haxelib run lime build android -release

      # -------------------------
      # Upload APK
      # -------------------------
      - name: Uploading APK
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine Android
          path: export/release/android/bin/*.apk
