name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Release Build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK 25c
        run: sdkmanager "ndk;25.2.9519653"

      - name: Set Android environment variables
        run: |
          echo "ANDROID_SDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          key: cache-build-android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/

      - run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

      - name: Installing/Updating libraries
        run: haxe -cp commandline -D analyzer-optimize --run Main setup -s

      - name: Setup Lime
        run: haxelib run lime setup android

      - name: Disable CI checks
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Build Android
        run: |
          mkdir -p build-logs
          haxelib run lime build android -release -D HXCPP_M64 -D HXCPP_NO_PARALLEL 2>&1 | tee build-logs/build.log | grep -iE "error:|undefined reference|ld:|collect2:" || true

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: Android Build Logs
          path: build-logs/build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android Build
          path: export/release/android/bin/*.apk

      - name: Clear cache
        uses: actions/github-script@v7
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-android") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
           

      - name: Upload new cache
        uses: actions/cache@v4
        with:
          key: cache-build-android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/
