name: Android Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Haxe 4.3.4
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK 25c
        run: sdkmanager "ndk;25.2.9519653"

      - name: Set NDK Path
        run: echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Setup Engine
        run: |
          haxe -cp commandline --run Main setup
          haxelib run lime setup android
          haxelib run lime rebuild hxcpp android

      - name: Build Release APK
        run: lime build android -release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: export/release/android/bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
